name: Prepare Build Environment
description: Installs required JDKs for building and testing
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

  - name: 'Set up JDK 8'
    uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
    with:
      distribution: 'liberica'
      java-version: 8

  - name: Prepare JDK8 env var
    shell: bash
    run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV

  - name: 'Set up JDK 17'
    uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
    with:
      distribution: 'temurin'
      java-version: 17

  - name: Prepare JDK17 env var
    shell: bash
    run: echo "JDK17=$JAVA_HOME" >> $GITHUB_ENV
