[versions]
kotlin = "1.8.20"
groovy = "4.0.13"

[libraries]
groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }

[plugins]
mavenPluginDevelopment = { id = "de.benediktritter.maven-plugin-development", version = "0.4.2" }
