[versions]
kotlin = "1.8.20"
groovy = "3.0.17"
spock = "2.3-groovy-3.0"

[libraries]
groovy-bom = { module = "org.codehaus.groovy:groovy-bom", version.ref = "groovy" }
groovy-nio.module = "org.codehaus.groovy:groovy-nio"
spock-bom =  { module = "org.spockframework:spock-bom", version.ref = "spock" }

[plugins]
mavenPluginDevelopment = { id = "de.benediktritter.maven-plugin-development", version = "0.4.2" }
