/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.gradle.cucumber.companion

import org.gradle.api.Project
import org.gradle.api.Plugin

class CucumberCompanionPlugin: Plugin<Project> {
    override fun apply(project: Project) {
    }
}
