name: 'Verify Team City Config'

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '.teamcity/**'

jobs:
  verfy-team-city-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Set up JDK 21
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: ./.teamcity
      run: mvn --batch-mode teamcity-configs:generate
