name: 'Cross Version Tests'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  cross-version-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    steps:
    - uses: actions/checkout@v4
    - name: "Setup Build Environment"
      uses: ./.github/actions/setup-environment

    - name: 'Run all Cross Version Tests'
      uses: gradle/gradle-build-action@v3
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_KEY }}
      with:
        arguments: "allMavenCrossVersionTests allGradleCrossVersionTests  --no-configuration-cache"

    - name: Store reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cross-version-reports-${{ matrix.os }}
        path: |
          **/build/reports/
          **/build/test-results/
