name: 'Cross Version Tests'

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    cross-version-tests:
        runs-on: 'ubuntu-latest'
        steps:
            - uses: actions/checkout@v3
            - name: "Setup Build Environment"
              uses: ./.github/actions/setup-environment

            - name: 'Run all Cross Version Tests'
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: "allMavenCrossVersionTests allGradleCrossVersionTests"
