name: 'Verify'

on:
    push:
    pull_request:
        branches:
            - '*'

jobs:
    build-and-verify:
        runs-on: 'ubuntu-latest'
        strategy:
            fail-fast: false
            matrix:
                java: ['11']
        steps:
            - uses: actions/checkout@v2
            - name: 'Set up JDK ${{ matrix.java }}'
              uses: actions/setup-java@v2
              if: matrix.java != 8
              with:
                  distribution: 'adopt'
                  java-version: ${{ matrix.java }}
            - name: 'Prepare JDK${{ matrix.java }} env var'
              shell: bash
              run: echo "JDK${{ matrix.java }}=$JAVA_HOME" >> $GITHUB_ENV

            - name: 'Set up JDK 8'
              uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: 8
            - name: Prepare JDK8 env var
              shell: bash
              run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV

            - name: 'Build Cucumber-Companion'
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: "functionalTest"
