name: 'Verify'

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

# https://stackoverflow.com/a/72408109/16358266
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-verify:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: "Setup Build Environment"
      uses: ./.github/actions/setup-environment

    - name: 'Setup Gradle'
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4
      with:
        develocity-access-key: ${{ secrets.DEVELOCITY_GRADLE_ORG_ACCESS_KEY }}

    - name: 'Check Cucumber-Companion'
      run: ./gradlew check  --no-configuration-cache
      env:
        DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_GRADLE_ORG_ACCESS_KEY }} # needed for remote cache push enablement

    - name: Store reports
      if: failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: check-reports-${{ matrix.os }}
        path: |
          **/build/reports/
          **/build/test-results/
