name: 'Verify Publications'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build-and-verify:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: "Setup Build Environment"
      uses: ./.github/actions/setup-environment

    - name: 'Build Cucumber-Companion'
      uses: gradle/gradle-build-action@v3
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_KEY }}
      with:
        arguments: "verifyPublication --no-configuration-cache"
